library(tm)

library(qdapDictionaries)
library(RColorBrewer)
library(data.table)
library(qdapTools)
library(chron)
library(XML)
library(dplyr)
library(gdata)
library(gtools)
library(gender)
library(NLP)
library(openNLP)
library(gridExtra)
library(openNLPdata)
library(rJava)
library(plotrix)
library(venneuler)
library(qdap)
dest = "C:/Users/Karthik/Documents/posts/"
files = list.files(path = dest, pattern = "pdf", full.names = TRUE)
sapply(files, FUN = function(i){
  file.rename(from = i, to = paste0(dirname(i),"/",gsub(" ", "",basename(i))))
})})
files = list.files(path=dest,pattern = "pdf",full.names = TRUE)
lapply(files, function(i) system(paste("./xpdfbin-win-3.04/xpdfbin-win-3.04/bin64/pdftotext.exe", paste0('"', i, '"')), wait = FALSE) )
